[config]
additional_profiles = ["release"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.check]
command = "cargo"
args = ["check"]

# WASM

[tasks.wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-emscripten", "${@}"]

[tasks.wasm-xargo]
command = "rustup"
args = ["run", "nightly", "xargo", "build", "-Zbuild-std", "--target", "wasm32-unknown-emscripten", "${@}"]

# [tasks.wasm-debug]
# private = true
# command = "cargo"
# args = ["build", "--target", "wasm32-unknown-emscripten"]
# env = { EMCC_CFLAGS = "--bind" }

# [tasks.wasm-release]
# private = true
# command = "cargo"
# args = ["build", "--target", "wasm32-unknown-emscripten", "--release"]
# env = { EMCC_CFLAGS = "--bind -O3" }

# iOS

[tasks.ios-device]
command = "cargo"
args = ["build", "--target", "aarch64-apple-ios", "--features", "mobile", "${@}"]

[tasks.ios-simulator]
command = "cargo"
args = ["build", "--target", "x86_64-apple-ios", "--features", "mobile", "${@}"]

[tasks.ios]
dependencies = ["ios-device", "ios-simulator"]

# Android
[tasks.android-armv7]
command = "cargo"
args = ["build", "--target", "armv7-linux-androideabi", "--features", "mobile", "${@}"]

[tasks.android-armv8]
command = "cargo"
args = ["build", "--target", "aarch64-linux-android", "--features", "mobile", "${@}"]

[tasks.android-x86]
command = "cargo"
args = ["build", "--target", "x86_64-linux-android", "--features", "mobile", "${@}"]

[tasks.android-i686]
command = "cargo"
args = ["build", "--target", "i686-linux-android", "--features", "mobile", "${@}"]

[tasks.android]
dependencies = ["android-armv7", "android-armv8", "android-x86", "android-i686"]

# Mobile
[tasks.mobile]
dependencies = ["android", "ios"]

# ALL OF THE THINGS
[tasks.all]
dependencies = ["mobile", "wasm"]
