[config]
additional_profiles = ["release"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.check]
command = "cargo"
args = ["check"]

# WASM

[tasks.wasm]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-emscripten", "${@}"]

# [tasks.wasm-debug]
# private = true
# command = "cargo"
# args = ["build", "--target", "wasm32-unknown-emscripten"]
# env = { EMCC_CFLAGS = "--bind" }

# [tasks.wasm-release]
# private = true
# command = "cargo"
# args = ["build", "--target", "wasm32-unknown-emscripten", "--release"]
# env = { EMCC_CFLAGS = "--bind -O3" }

# iOS

[tasks.ios]
command = "cargo"
args = ["build", "--target", "aarch64-apple-ios", "--features", "mobile", "${@}"]

# Android
[tasks.android-armv7]
command = "cargo"
args = ["build", "--target", "armv7-linux-android", "--features", "mobile", "${@}"]

[tasks.android-armv8]
command = "cargo"
args = ["build", "--target", "aarch64-linux-android", "--features", "mobile", "${@}"]

[tasks.android]
dependencies = ["android-armv7", "android-armv8"]

# Mobile
[tasks.mobile]
dependencies = ["android", "ios"]

# ALL OF THE THINGS
[tasks.all]
dependencies = ["mobile", "wasm"]
