[workspace]
members = ["crypto", "keystore", "mls-provider"]
exclude = ["anycrypto", "core-ds"]

[patch.crates-io.proteus]
git = "https://github.com/wireapp/proteus"
branch = "otak/sodiumoxide-0.2.7"

[profile.release]
lto = true
