[workspace]
members = ["crypto", "crypto-ffi", "keystore", "mls-provider", "core-ds"]
exclude = ["anycrypto"]

[patch.crates-io.proteus]
git = "https://github.com/wireapp/proteus"
branch = "otak/sodiumoxide-0.2.7"

[profile.release]
lto = true
