[env]
EMCC_CFLAGS = "--bind -O3"

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=./crypto-ffi/support/gxx_personality_v0_stub.o",
    "-C", "link-args=--export-all",
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Wl,--no-entry",
]
