[package]
name = "core-crypto-keystore"
version = "0.1.0"
edition = "2021"

[lib]
name = "core_crypto_keystore"
crate-type = ["lib", "cdylib"]

[dependencies]
eyre = "0.6"
thiserror = "1.0"
uuid = "0.8"
lru = "0.7"
barrel = { version = "0.7", features = ["sqlite3"] }

[dependencies.rusqlite]
version = "0.26"
default-features = false
features = ["bundled-sqlcipher-vendored-openssl", "blob", "wasm32-wasi-vfs", "uuid"]

[dependencies.refinery]
git = "https://github.com/rust-db/refinery"
branch = "main"
features = ["rusqlite"]

[dependencies.openmls]
git = "https://github.com/openmls/openmls"
branch = "main"
default-features = false

[dependencies.openmls_traits]
git = "https://github.com/openmls/openmls"
branch = "main"

[dependencies.proteus]
git = "https://github.com/wireapp/proteus"
branch = "otak/sodiumoxide-0.2.7"
