[package]
name = "core-crypto-keystore"
version = "0.1.1"
edition = "2021"

[lib]
name = "core_crypto_keystore"
crate-type = ["lib", "cdylib"]

[[bench]]
name = "read"
harness = false

[[bench]]
name = "write"
harness = false

[features]
default = ["memory-cache"]
ios-wal-compat = ["aes", "hex"]
memory-cache = ["lru"]
proteus-keystore = ["proteus"]

[dependencies]
eyre = "0.6"
thiserror = "1.0"
uuid = { version = "0.8", default-features = false }
lru = { version = "0.7", optional = true }
refinery = { version = "0.8", default-features = false, features = ["rusqlite"] }
barrel = { version = "0.7", features = ["sqlite3"] }

# iOS specific things
aes = { version = "0.7", optional = true }
hex = { version = "0.4", optional = true }

openmls_traits = { git = "https://github.com/openmls/openmls" }
proteus = { version = "1.0", default-features = false, optional = true }

[target.wasm32-unknown-emscripten.dependencies.rusqlite]
version = "0.26"
default-features = false
features = ["bundled-sqlcipher-vendored-openssl", "blob", "wasm32-wasi-vfs", "uuid"]

[target.'cfg(not(target = "wasm32-unknown-emscripten"))'.dependencies.rusqlite]
version = "0.26"
default-features = false
features = ["bundled-sqlcipher", "blob", "uuid"]

[dev-dependencies]
criterion = "0.3"
openmls = { git = "https://github.com/openmls/openmls", default-features = false }
openmls_rust_crypto_provider = { git = "https://github.com/openmls/openmls", package = "openmls_rust_crypto", default-features = false }
