[package]
name = "core-crypto"
version = "0.1.0"
edition = "2021"

[lib]
name = "core_crypto"
crate-type = ["lib", "cdylib"]

[dependencies]
eyre = "0.6"
thiserror = "1.0"
uuid = { version = "1.0.0-alpha", features = ["v5"] }
derive_builder = "0.10"

openmls = "0.4.0-pre"
openmls_traits = "0.1.0-pre"

[dependencies.core-crypto-keystore]
version = "0.1.0"
path = "../keystore"

[dependencies.mls-crypto-provider]
version = "0.1.0"
path = "../mls-provider"

[dev-dependencies]
uuid = { version = "1.0.0-alpha", features = ["v4", "v5"] }
rand = "0.8"
